/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8-dev at Fri Nov 25 21:22:27 2016. */

#include "public.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t IndexType_fields[7] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, IndexType, tid, tid, 0),
    PB_FIELD(  2, STRING  , SINGULAR, CALLBACK, OTHER, IndexType, code, tid, 0),
    PB_FIELD(  3, STRING  , SINGULAR, CALLBACK, OTHER, IndexType, name, code, 0),
    PB_FIELD(  4, STRING  , SINGULAR, CALLBACK, OTHER, IndexType, icon_m, name, 0),
    PB_FIELD(  5, STRING  , SINGULAR, CALLBACK, OTHER, IndexType, icon_s, icon_m, 0),
    PB_FIELD(  6, BYTES   , REPEATED, CALLBACK, OTHER, IndexType, as, icon_s, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
